{{- if .Values.configmaps.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-data
  labels:
    app: {{ template "kafka-exporter.name" . }}
    chart: {{ template "kafka-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- $files := .Files }}
{{ range .Values.configmaps.files }}
  {{ . }}: |
{{ $files.Get . | indent 4 }}
{{ end }}
{{- end }}
