# Default values for modules-ms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

annotations:
   hpa.autoscaling.banzaicloud.io/maxReplicas: 10
   hpa.autoscaling.banzaicloud.io/minReplicas: 1
   prometheus.customMetricName.hpa.autoscaling.banzaicloud.io/query: 10
   prometheus.customMetricName.hpa.autoscaling.banzaicloud.io/targetValue: 10

envVars:
  - name: SPRING_CLOUD_CONSUL_HOST
    value: "consul-server.default.svc.cluster.local"
  - name: SPRING_CLOUD_CONSUL_PORT
    value: "2"

image:
  repository: realwave-backoffice-middleware
  tag: latest
  pullPolicy: IfNotPresent

service:
  ports:
  - name: http
    port: 8080
  - name: grpc
    port: 7073
  type: ClusterIP
  name: demo-application
  

configmaps:
  enabled: false

startcommand: 
  enabled: false
  value: ["/bin/sh","-c","sleep infinity"]

ingress:
  enabled: false
  annotations: 
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  path: /health
  hosts:
    - name: k8s-service.demo.io
      port: http

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
    cpu: 100m
    memory: 128Mi
   requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

hpa:
  enabled: false

annotations:
  - name: hpa.autoscaling.banzaicloud.io/maxReplicas
    value: 10
  - name: hpa.autoscaling.banzaicloud.io/minReplicas
    value: 1
  - name: cpu.hpa.autoscaling.banzaicloud.io/targetAverageUtilization
    value: 85
  - name: prometheus.customMetricName.hpa.autoscaling.banzaicloud.io/query
    value: "example"
  - name: prometheus.customMetricName.hpa.autoscaling.banzaicloud.io/targetAverageValue
    value: "100"

imageCredentials:
  registry: realwavelab.azurecr.io

vault:
  enabled: false
  policy: wallet-policy
  host: vault-lab.apirealwave.io

livenessProbe:
  enabled: false
  failureThreshold: 3
  httpGet:
    path: /health-check
    port: 8020
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health-check
    port: 8020
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1

consulnode:
  enabled: false
  repository: realwave-node-consul
  path: /etc/test 

