{{- if .Values.ingress.enabled -}}
{{- $fullName := include "modules-ms.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $serviceName := .Values.service.name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "modules-ms.name" . }}
    chart: {{ template "modules-ms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{ range $i, $var := .Values.ingress.hosts }}
  - host: {{ $var.name }}
    http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $var.port }}
  {{- end }}
{{- end }}